name: Generate Swagger Docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  generate-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'

      - name: Install swag CLI
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate swagger docs
        working-directory: ./backend
        run: swag init -g ./cmd/server/main.go

      - name: Commit and push docs if changed
        working-directory: ./backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          if ! git diff --cached --quiet; then
            git commit -m "ci: auto generate swagger docs"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi

      - name: Generate TypeScript types from OpenAPI
        run: |
          npm install -g openapi-typescript
          openapi-typescript backend/docs/swagger.json --output frontend/src/types/api.d.ts

